### ISSUE TITLE
关于jwt中的cookie问题

### ISSUE THREAD

**Issue by salmon002** [springleng/slim3-fw-for-api#1]
有幸拜读您的代码， 有个问题需要请教一下，如果是rest api做登录请求， 他是不携带cookie信息，源码里面setcookie的方式保存token还有意义吗

**Comment by springleng** [comment]
@salmon002 你可以看看这个组件的使用https://github.com/tuupola/slim-jwt-auth
我这边目前的项目用的是cookie这种方式

**Comment by salmon002** [comment]
thx， 那您这边就没用restful api请求数据是吧

**Comment by springleng** [comment]
@salmon002 是restful api的，我这边的项目用的是浏览器，登陆之后把token保存到cookie中，浏览器每次访问会带着cookie访问接口

**Comment by salmon002** [comment]
了解，谢谢
